// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZCKIVBZYyUlpnHtjvoyipalVB4N-sCFE',
    appId: '1:446832460136:web:8bc3d020f49eeae48316dd',
    messagingSenderId: '446832460136',
    projectId: 'ecodiveai-af9de',
    authDomain: 'ecodiveai-af9de.firebaseapp.com',
    storageBucket: 'ecodiveai-af9de.firebasestorage.app',
    measurementId: 'G-NGKYED8KKM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmM6S4-9dnzECs8hRcVtbDVlzp9kM3xP0',
    appId: '1:446832460136:android:a5f7e0a56125f0a18316dd',
    messagingSenderId: '446832460136',
    projectId: 'ecodiveai-af9de',
    storageBucket: 'ecodiveai-af9de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqr29JOTbkhH7HDz6bX1N-8E4uVumKF_U',
    appId: '1:446832460136:ios:31fe157286639e3e8316dd',
    messagingSenderId: '446832460136',
    projectId: 'ecodiveai-af9de',
    storageBucket: 'ecodiveai-af9de.firebasestorage.app',
    iosBundleId: 'com.example.ecodiveAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqr29JOTbkhH7HDz6bX1N-8E4uVumKF_U',
    appId: '1:446832460136:ios:31fe157286639e3e8316dd',
    messagingSenderId: '446832460136',
    projectId: 'ecodiveai-af9de',
    storageBucket: 'ecodiveai-af9de.firebasestorage.app',
    iosBundleId: 'com.example.ecodiveAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZCKIVBZYyUlpnHtjvoyipalVB4N-sCFE',
    appId: '1:446832460136:web:c4aa98420053e2608316dd',
    messagingSenderId: '446832460136',
    projectId: 'ecodiveai-af9de',
    authDomain: 'ecodiveai-af9de.firebaseapp.com',
    storageBucket: 'ecodiveai-af9de.firebasestorage.app',
    measurementId: 'G-ZRDC8VBEM8',
  );
}
